return {
    -- 游戏玩法规则
  _gamePalyingName={
    [1] = {title = "keqianggh",                               ch = "可抢杠胡"},
    [2] = {title = "minggangkq",                              ch = "明杠可抢"},
    [3] = {title = "qgqb",                             ch = "抢杠全包"},
    [4] = {title = "gangbaoqb",                               ch = "杠爆全包"},
    [5] = {title = "sghp",                         ch = "四鬼胡牌"},
    [6] = {title = "sghp2b",                         ch = "2倍"},
    [7] = {title = "pph",                              ch = "碰碰胡2倍"},
    [8] = {title = "qingyise",                                ch = "清一色4倍"},
    [9] = {title = "yj",                                  ch = "幺九6倍"},
    [10] = {title = "hyj",                              ch = "含19即可"},
    [11] = {title = "quanfeng",                               ch = "全风8倍"},
    [12] = {title = "hunyise",                                ch = "混一色2倍"},
    [13] = {title = "qidui",                                  ch = "七对4倍"},
    [14] = {title = "gz",                              ch = "跟庄"},
    [15] = {title = "mgd",                                ch = "马跟底分"},
    [16] = {title = "mgg",                              ch = "马跟杠"},
    [17] = {title = "wg",                                  ch = "无鬼"},
    [18] = {title = "bbzg",                           ch = "白板做鬼"},
    [19] = {title = "fg",                                 ch = "翻鬼"},
    [20] = {title = "wgjb",                            ch = "无鬼加倍"},
    [21] = {title = "wuma",                                  ch = "无马"},
    [22] = {title = "erma",                                   ch = "2马"},
    [23] = {title = "sima",                                   ch = "4马"},
    [24] = {title = "liuma",                                  ch = "6马"},
    [25] = {title = "guipai",                                 ch = "鬼牌"},
    [26] = {title = "mapai",                                  ch = "马牌"}, 
}
}