-------------------------------------------------------------------------
-- Desc:   二人斗地主扑克牌框架网络消息id 继承扑克公用消息id
-- Last:
-- Author:   faker
-- Content:  
-- 2017-11-04  新建
-- 2017-11-07  修改 区分队列消息和普通直传消息
-------------------------------------------------------------------------
DDZTWOPSocketCmd = require("package_src.games.pokercommon.data.PokerCommonSocketCmd");
DDZTWOPSocketCmd.CODE_REC_GAMESTART = 32012; --游戏开始
DDZTWOPSocketCmd.CODE_REC_CALLLORD = 32011; --叫地主
DDZTWOPSocketCmd.CODE_SEND_CALLLORD = 32011;
DDZTWOPSocketCmd.CODE_REC_DOUBLE = 32013; --加倍
DDZTWOPSocketCmd.CODE_SEND_DOUBLE = 32013;
DDZTWOPSocketCmd.CODE_REC_ROBLORD = 32014; --抢地主
DDZTWOPSocketCmd.CODE_SEND_ROBLORD = 32014;
DDZTWOPSocketCmd.CODE_REC_MINGPAI = 32015; --明牌
DDZTWOPSocketCmd.CODE_SEND_MINGPAI = 32015;
DDZTWOPSocketCmd.CODE_REC_STARTPLAY = 32003; --开始打牌
DDZTWOPSocketCmd.CODE_REC_OUTCARD = 32010; --出牌
DDZTWOPSocketCmd.CODE_SEND_OUTCARD = 32010;
DDZTWOPSocketCmd.CODE_REC_GAMEOVER = 32020; -- 游戏结束
DDZTWOPSocketCmd.CODE_REC_RECONNECT = 32016; --重新连接

DDZTWOPSocketCmd.CODE_UPDATE_CASH = 30002;
DDZTWOPSocketCmd.CODE_TUOGUAN = 30008;
DDZTWOPSocketCmd.CODE_USER_CHAT = 30009;
DDZTWOPSocketCmd.CODE_DEFAULT_CHAT = 30010;
DDZTWOPSocketCmd.CODE_REC_ExitRoom = 20014; 
DDZTWOPSocketCmd.CODE_REC_RESUMEGAME= 30005; --恢复游戏对局结果
DDZTWOPSocketCmd.CODE_USERDATA_POINT= 1003; --用户账户信息
DDZTWOPSocketCmd.CODE_REC_PAOMADENG= 60012;    --跑马灯
DDZTWOPSocketCmd.CODE_REC_GETORDER= 90002;    --获取订单号
DDZTWOPSocketCmd.CODE_REC_CHARGERESULT = 90003;    --支付成功


--注册委托监听消息
DDZTWOPSocketCmd.msgsBindRecv = {
	DDZTWOPSocketCmd.CODE_REC_GAMESTART,
	DDZTWOPSocketCmd.CODE_REC_CALLLORD,
	DDZTWOPSocketCmd.CODE_REC_ROBLORD,
	DDZTWOPSocketCmd.CODE_REC_STARTPLAY,
	DDZTWOPSocketCmd.CODE_REC_OUTCARD,
	DDZTWOPSocketCmd.CODE_REC_GAMEOVER,
	DDZTWOPSocketCmd.CODE_REC_TOTAL_GAME_OVER
	--DDZTWOPSocketCmd.CODE_REC_RESUMEGAME, --TODO 这条消息不知道是否存在  
}

DDZTWOPSocketCmd.msgsCommonBindRecv = {
	DDZTWOPSocketCmd.CODE_USERDATA_POINT,
	DDZTWOPSocketCmd.CODE_UPDATE_CASH,
	DDZTWOPSocketCmd.CODE_TUOGUAN,
	DDZTWOPSocketCmd.CODE_DEFAULT_CHAT,
	DDZTWOPSocketCmd.CODE_USER_CHAT,
	DDZTWOPSocketCmd.CODE_REC_RECONNECT,
	DDZTWOPSocketCmd.CODE_REC_ExitRoom,

	DDZTWOPSocketCmd.CODE_REC_PAOMADENG,

	DDZTWOPSocketCmd.CODE_REC_GETORDER,
	DDZTWOPSocketCmd.CODE_REC_CHARGERESULT,

	DDZTWOPSocketCmd.CODE_REC_ENTERROOM,

	DDZTWOPSocketCmd.CODE_REC_POKERDIALOG,
	DDZTWOPSocketCmd.CODE_REC_SAY_CHAT,
	DDZTWOPSocketCmd.CODE_REC_CONTINUE,
	DDZTWOPSocketCmd.CODE_FRIEND_ROOM_LEAVE,
	DDZTWOPSocketCmd.CODE_RECV_FRIEND_ROOM_END,
	DDZTWOPSocketCmd.CODE_REC_BROCAST, --通知
	DDZTWOPSocketCmd.CODE_RECV_FRIEND_ROOM_INFO,
}